= Rust Program for Premier League Standings

This program retrieves the Premier League standings from the Football-Data API and displays them in a table using the prettytable crate.

== Getting Started

=== Prerequisites

To run this program, you will need to have Rust and Cargo installed on your machine. You can install Rust and Cargo by following the instructions link:https://www.rust-lang.org/learn/get-started[here].

=== Installation

Clone the repository:
[source,shell]
$ git clone https://github.com/codewankenobi/premier-league-standings.git

Change into the project directory:
[source,shell]
$ cd premier-league-standings

Create a .env file in the root directory of the project and add your Football-Data API token:
[source,shell]
API_TOKEN=your-api-token-here

=== Usage

To run the program, execute the following command in your terminal:
[source,shell]
$ cargo run

The program will retrieve the Premier League standings from the Football-Data API and display them in a table in your terminal.

== License

This project is licensed under the MIT License.