= Premier League Standings

A simple console application written in Rust that displays you a detailed table of the current Premier League standings. The data is received from the link:https://www.football-data.org/[Football-Data API]. For printing the table link:https://crates.io/crates/prettytable-rs[prettytable-rs] crate is used.

== How to Run

=== Prerequisites

To run this program, you will need to have Rust and Cargo installed on your machine. You can install Rust and Cargo by following the instructions link:https://www.rust-lang.org/learn/get-started[here].

=== Installation

Clone the repository:
[source,shell]
$ git clone https://github.com/codewankenobi/premier-league-standings.git

Change into the project directory:
[source,shell]
$ cd premier-league-standings

Create a .env file in the root directory of the project and add your Football-Data API token:
[source,shell]
API_TOKEN=your-api-token-here

=== Usage

To run the program, execute the following command in your terminal:
[source,shell]
$ cargo run

The program will retrieve the Premier League standings from the Football-Data API and display them in a table in your terminal.

=== Alias

I recommend creating an alias in your shell configuration so you can run the program with less typing. For example for Fish shell:
[source,shell]
alias pl "PATH_TO_THE_PROJECT/premier-league-standings/target/release/premier-league-standings"

== License

This project is licensed under the MIT License.